// <auto-generated />
using System;
using JwtWebApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JwtWebApi.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("JwtWebApi.Model.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("loginModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "PasswordFistUser",
                            UserName = "FirstUser"
                        },
                        new
                        {
                            Id = 2,
                            Password = "PasswordSecond",
                            UserName = "SecondUser"
                        });
                });

            modelBuilder.Entity("JwtWebApi.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("loginModelId")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("loginModelId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            createDate = new DateTime(2021, 12, 11, 16, 29, 45, 81, DateTimeKind.Local).AddTicks(2485),
                            loginModelId = 1,
                            message = "some text from fist User"
                        },
                        new
                        {
                            Id = 2,
                            createDate = new DateTime(2021, 12, 11, 16, 29, 45, 82, DateTimeKind.Local).AddTicks(9321),
                            loginModelId = 1,
                            message = "some text 2 from fist User"
                        },
                        new
                        {
                            Id = 3,
                            createDate = new DateTime(2021, 12, 11, 16, 29, 45, 82, DateTimeKind.Local).AddTicks(9766),
                            loginModelId = 2,
                            message = "some text from second User"
                        });
                });

            modelBuilder.Entity("JwtWebApi.Model.Ticket", b =>
                {
                    b.HasOne("JwtWebApi.Model.LoginModel", "loginModel")
                        .WithMany("Tickets")
                        .HasForeignKey("loginModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loginModel");
                });

            modelBuilder.Entity("JwtWebApi.Model.LoginModel", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
