version: '3.4'

services:
  jwtwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - 'postgres'
    networks:
      - accman-network  

  postgres:
    ports:
      - '5432:5432'
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    image: 'postgres'
    networks:
      - accman-network

networks:
  accman-network:
    driver: bridge
