# Use postgres/example user/password credentials
version: '3.8'

services:

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
  	 POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 123456
	ports:
       - 5432:5432
 